version: "3.9"

networks:
  dockerapi-dev:
    driver: bridge 

services:
    api:
        container_name: api
        build: ./HappyX.Api/.
        ports:
            - "8083:8080"
        depends_on:
            - db
    db:
        container_name: db
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - '5432:5432'
        volumes:
            - db_volume:/var/lib/postgresql/data
            - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql

    web:
        container_name: web
        build: ./HappyX.Web/.
        ports:
            - "80:80"
    bot:
        container_name: bot
        build: ./HappyX.Bot/.
        ports:
            - "8084:80" 

volumes:
  db_volume: